#!/usr/bin/env bash
# 20-shell.sh — the ergonomics layer. These are the tools that make a terminal
# feel better than a GUI rather than worse, so they are all default-on.

register_group shell "Shell Ergonomics" \
  "Prompt, fuzzy history, smart cd, per-directory env. Install these first."

register_pkg \
  --id starship \
  --name "starship" \
  --desc "Fast prompt showing git branch/state and language versions" \
  --group shell \
  --check "command -v starship" \
  --install "install_script https://starship.rs/install.sh -y" \
  --config "_configure_starship" \
  --manual "curl -sS https://starship.rs/install.sh | sh" \
  --default yes

_configure_starship() {
  local cfg="$HOME/.config/starship.toml"
  if [[ -f "$cfg" ]]; then
    debug "starship.toml already exists; leaving it alone"
    return 0
  fi
  if [[ -f "$DEVUP_ROOT/configs/starship.toml" ]]; then
    if [[ "${DRY_RUN:-0}" == "1" ]]; then
      printf '%s\n' "${C_DIM}  [dry-run] install starship.toml${C_RESET}"
      return 0
    fi
    mkdir -p "$(dirname "$cfg")"
    cp "$DEVUP_ROOT/configs/starship.toml" "$cfg"
    success "Installed starship config"
  fi
}

register_pkg \
  --id atuin \
  --name "atuin" \
  --desc "Fuzzy searchable shell history — the single biggest QoL win" \
  --group shell \
  --check "command -v atuin" \
  --install "install_script https://setup.atuin.sh" \
  --manual "curl --proto '=https' --tlsv1.2 -LsSf https://setup.atuin.sh | sh" \
  --note "atuin stores history locally by default. Run 'atuin register' only if you want sync." \
  --default yes

register_pkg \
  --id zoxide \
  --name "zoxide" \
  --desc "Jump to any directory you've visited: 'z myproject'" \
  --group shell \
  --check "command -v zoxide" \
  --install "install_apt zoxide" \
  --manual "sudo apt install zoxide  # or: curl -sSfL https://webi.sh/zoxide | sh" \
  --default yes

register_pkg \
  --id direnv \
  --name "direnv" \
  --desc "Auto-load per-project env vars from .envrc" \
  --group shell \
  --check "command -v direnv" \
  --install "install_apt direnv" \
  --manual "sudo apt install direnv" \
  --default yes

register_pkg \
  --id shell-integration \
  --name "shell wiring" \
  --desc "Generate ~/.config/devup/shell.sh and source it from your rc files" \
  --group shell \
  --check "test -f \$HOME/.config/devup/shell.sh" \
  --install "true" \
  --config "_configure_shell_integration" \
  --manual "Source configs/shell.sh from your ~/.zshrc" \
  --default yes

# Generates a single managed init file, conditional on what is actually
# installed, then sources it from .zshrc and .bashrc via a marked block.
# Re-runnable: regenerating picks up newly installed tools.
_configure_shell_integration() {
  local out="$HOME/.config/devup/shell.sh"

  if [[ "${DRY_RUN:-0}" == "1" ]]; then
    printf '%s\n' "${C_DIM}  [dry-run] generate ${out} and hook it into ~/.zshrc + ~/.bashrc${C_RESET}"
    return 0
  fi

  mkdir -p "$(dirname "$out")"

  {
    cat <<'HEADER'
# Generated by devup. Re-run `devup config shell-integration` to regenerate.
# Safe to edit, but changes will be overwritten. Put your own tweaks in
# ~/.config/devup/local.sh instead — it is sourced at the end of this file.

# ---- PATH ----
case ":$PATH:" in
  *":$HOME/.local/bin:"*) ;;
  *) export PATH="$HOME/.local/bin:$PATH" ;;
esac

# Detect the current shell (zsh vs bash) for tool init.
if [ -n "${ZSH_VERSION:-}" ]; then _devup_shell="zsh"
elif [ -n "${BASH_VERSION:-}" ]; then _devup_shell="bash"
else _devup_shell="sh"
fi

# ---- editor ----
if command -v nvim >/dev/null 2>&1; then
  export EDITOR="nvim" VISUAL="nvim"
elif command -v vim >/dev/null 2>&1; then
  export EDITOR="vim" VISUAL="vim"
fi

HEADER

    # --- zsh plugins (apt paths) ---
    cat <<'ZPLUG'
# ---- zsh plugins ----
if [ "$_devup_shell" = "zsh" ]; then
  [ -f /usr/share/zsh-autosuggestions/zsh-autosuggestions.zsh ] && \
    . /usr/share/zsh-autosuggestions/zsh-autosuggestions.zsh
  [ -f /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh ] && \
    . /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

  # History behaviour
  HISTSIZE=100000
  SAVEHIST=100000
  HISTFILE="$HOME/.zsh_history"
  setopt HIST_IGNORE_ALL_DUPS HIST_REDUCE_BLANKS SHARE_HISTORY INC_APPEND_HISTORY
  setopt AUTO_CD AUTO_PUSHD PUSHD_IGNORE_DUPS INTERACTIVE_COMMENTS

  # Completion
  autoload -Uz compinit && compinit -C
  zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}'
  zstyle ':completion:*' menu select

  # Readline-style keys that survive on any machine
  bindkey -e
  bindkey '^[[1;5C' forward-word
  bindkey '^[[1;5D' backward-word
fi

ZPLUG

    # --- mise (must come before language-specific bits) ---
    if command -v mise >/dev/null 2>&1 || [[ -x "$HOME/.local/bin/mise" ]]; then
      cat <<'MISE'
# ---- mise (Go / Node / Python versions) ----
if command -v mise >/dev/null 2>&1; then
  case "$_devup_shell" in
    zsh)  eval "$(mise activate zsh)" ;;
    bash) eval "$(mise activate bash)" ;;
  esac
fi

MISE
    fi

    # --- rust ---
    if [[ -d "$HOME/.cargo" ]]; then
      cat <<'RUST'
# ---- rust ----
[ -f "$HOME/.cargo/env" ] && . "$HOME/.cargo/env"
export CARGO_TARGET_DIR="$HOME/.cache/cargo-target"

RUST
    fi

    # --- pnpm ---
    if command -v pnpm >/dev/null 2>&1 || [[ -d "$HOME/.local/share/pnpm" ]]; then
      cat <<'PNPM'
# ---- pnpm ----
export PNPM_HOME="$HOME/.local/share/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac

PNPM
    fi

    # --- go ---
    cat <<'GO'
# ---- go ----
export GOPATH="${GOPATH:-$HOME/go}"
case ":$PATH:" in
  *":$GOPATH/bin:"*) ;;
  *) export PATH="$GOPATH/bin:$PATH" ;;
esac

GO

    # --- zoxide ---
    if command -v zoxide >/dev/null 2>&1; then
      cat <<'ZOXIDE'
# ---- zoxide ----
case "$_devup_shell" in
  zsh)  eval "$(zoxide init zsh)" ;;
  bash) eval "$(zoxide init bash)" ;;
esac

ZOXIDE
    fi

    # --- fzf ---
    if command -v fzf >/dev/null 2>&1; then
      cat <<'FZF'
# ---- fzf ----
if command -v fd >/dev/null 2>&1; then
  export FZF_DEFAULT_COMMAND='fd --type f --hidden --follow --exclude .git'
  export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
elif command -v rg >/dev/null 2>&1; then
  export FZF_DEFAULT_COMMAND='rg --files --hidden --glob "!.git/*"'
fi
export FZF_DEFAULT_OPTS='--height 45% --layout=reverse --border --info=inline'
if command -v bat >/dev/null 2>&1; then
  export FZF_CTRL_T_OPTS="--preview 'bat -n --color=always --line-range :300 {}'"
fi
# fzf >= 0.48 ships shell integration; older versions use the sourced scripts.
if fzf --version >/dev/null 2>&1 && fzf --zsh >/dev/null 2>&1; then
  case "$_devup_shell" in
    zsh)  eval "$(fzf --zsh)" ;;
    bash) eval "$(fzf --bash)" ;;
  esac
else
  [ -f /usr/share/doc/fzf/examples/key-bindings.zsh ] && [ "$_devup_shell" = "zsh" ] && \
    . /usr/share/doc/fzf/examples/key-bindings.zsh
  [ -f /usr/share/doc/fzf/examples/key-bindings.bash ] && [ "$_devup_shell" = "bash" ] && \
    . /usr/share/doc/fzf/examples/key-bindings.bash
fi

FZF
    fi

    # --- direnv ---
    if command -v direnv >/dev/null 2>&1; then
      cat <<'DIRENV'
# ---- direnv ----
case "$_devup_shell" in
  zsh)  eval "$(direnv hook zsh)" ;;
  bash) eval "$(direnv hook bash)" ;;
esac

DIRENV
    fi

    # --- starship (prompt last, so nothing overwrites it) ---
    if command -v starship >/dev/null 2>&1; then
      cat <<'STARSHIP'
# ---- starship ----
case "$_devup_shell" in
  zsh)  eval "$(starship init zsh)" ;;
  bash) eval "$(starship init bash)" ;;
esac

STARSHIP
    fi

    # --- atuin (after starship: it rebinds Ctrl-R and the up arrow) ---
    if command -v atuin >/dev/null 2>&1; then
      cat <<'ATUIN'
# ---- atuin ----
case "$_devup_shell" in
  zsh)  eval "$(atuin init zsh --disable-up-arrow)" ;;
  bash) eval "$(atuin init bash --disable-up-arrow)" ;;
esac

ATUIN
    fi

    # --- aliases ---
    cat <<'ALIASES'
# ---- aliases ----
# Deliberately conservative: shortcuts for things you already know how to
# type, so you stay able to work on a machine that doesn't have your dotfiles.
if command -v eza >/dev/null 2>&1; then
  alias ls='eza --group-directories-first'
  alias ll='eza -l --git --group-directories-first'
  alias la='eza -la --git --group-directories-first'
  alias lt='eza --tree --level=2 --group-directories-first'
else
  alias ll='ls -lh'
  alias la='ls -lah'
fi

# Deliberately NOT aliasing `cat` or `du`: their flags differ from bat/dust,
# and shadowing standard commands is how you end up unable to work on a
# machine that isn't yours.
command -v batcat >/dev/null 2>&1 && ! command -v bat >/dev/null 2>&1 && alias bat='batcat'
command -v fdfind >/dev/null 2>&1 && ! command -v fd >/dev/null 2>&1 && alias fd='fdfind'
command -v lazygit >/dev/null 2>&1 && alias lg='lazygit'
command -v lazydocker >/dev/null 2>&1 && alias lzd='lazydocker'

alias gs='git status -sb'
alias gd='git diff'
alias gds='git diff --staged'
alias gap='git add -p'
alias gco='git checkout'
alias gp='git push'
alias gl='git log --oneline --graph --decorate -20'

alias dc='docker compose'
alias dps='docker ps --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}"'

alias ..='cd ..'
alias ...='cd ../..'
alias mkdir='mkdir -p'

# Which process is on a port? — the lookup everyone needs weekly.
port() { lsof -i ":$1" 2>/dev/null || ss -ltnp 2>/dev/null | grep ":$1"; }

# ---- local overrides ----
[ -f "$HOME/.config/devup/local.sh" ] && . "$HOME/.config/devup/local.sh"

unset _devup_shell
ALIASES
  } >"$out"

  success "Generated $out"

  # Hook it into the rc files.
  local hook='[ -f "$HOME/.config/devup/shell.sh" ] && . "$HOME/.config/devup/shell.sh"'
  local rc
  for rc in "$HOME/.zshrc" "$HOME/.bashrc"; do
    [[ -f "$rc" ]] || touch "$rc"
    write_block "$rc" "shell" "$hook"
  done
  success "Hooked into ~/.zshrc and ~/.bashrc"

  touch "$HOME/.config/devup/local.sh"
}
