# desc: Optional GNOME desktop customization with the user's preferred extensions.

gnome-extension-manager
gnome-extensions-cli
gnome-just-perfection
gnome-user-themes
gnome-wallpaper-slideshow
gnome-chromaleon
gnome-dash-to-dock
gnome-blur-my-shell
gnome-top-bar-organizer
gnome-lockscreen-clock
gnome-gsconnect
gnome-tiling-shell
gnome-search-light
